### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by galipmedia** [crrobinson14/vue-rethinkdb#2] opened 2018-06-27 14:04 UTC
Hi thanks for answering my last question so thoroughly. I understand if this may be too much to answer but I would love to get this working, so here are the issues I am facing...

1. The example query using 'value' doesn't work for me
```
rethinkDB() {
            return {
                user: { value: 'getUser', params: { userId: this.userId } }
                      }
}
``` 
results in an error where the query is undefined. I am assuming 'value' is to be used to get an object while 'collection' is to get an array of objects.

```
DEBUGGER:
RethinkDB: Registering field user 
Object { config: {…}, query: {…} }
vue-rethinkdb.js:332
RethinkDB: Subscribing to query 
Object { queryId: 1, vm: {…}, field: "user", query: undefined, params: {…}, state: "initializing", onStateChanged: null, onValueChanged: null, onEntryAdded: null, onEntryUpdated: null, … }
```

2. Results are reactive but adding to the total array rather than replacing it
```
rethinkDB() {
            return {
                users: {collection: 'getUsers'},
                       }
}

-------------

<div v-for="user in users" :key="user.id">
    <h1>{{user.firstName}}</h1>
    </div>
``` 

Initially shows the records but upon adding one in the database it reacts but shows the original set and the new set. eg Bob, Bill, Jane => Bob, Bill, Jane, Bob, Bill, Jane, Tom

3. Queries are being run twice which is resulting in the second one having a duplicate query ID.
```
RethinkDB: Connection established, sending handshake...
vue-rethinkdb.js:268
RethinkDB: Registering field users 
Object { config: {…}, query: {…} }
vue-rethinkdb.js:332
RethinkDB: Subscribing to query 
Object { queryId: 1, vm: {…}, field: "users", query: "getUsers", params: {}, state: "initializing", onStateChanged: null, onValueChanged: null, onEntryAdded: null, onEntryUpdated: null, … }
vue-rethinkdb.js:366
RethinkDB: Skipping authentication
vue-rethinkdb.js:533
RethinkDB: Subscribing to all
vue-rethinkdb.js:359
RethinkDB: Subscribing to query 
Object { queryId: 1, vm: {…}, field: "users", query: "getUsers", params: {}, state: "initializing", onStateChanged: null, onValueChanged: null, onEntryAdded: null, onEntryUpdated: null, … }
vue-rethinkdb.js:366
RethinkDB: Unhandled WebSocket message 
Object { rid: 3, error: "Invalid query: missing or duplicate queryId: 1" }
```
Sorry :)

**Comment by galipmedia** [comment] 2018-07-26 10:43
#1 is a bug in the code on line 321 of vue-rethinkdb.js, config.query should be config.value ...
` query: config.value || config.collection,`

#2 just fixed itself upon restarting everything.

#3 duplicate id still occurring as above any ideas how to stop this error? It doesn't effect the functionality but prints ugly errors into the console.

**Comment by crrobinson14** [comment] 2018-07-31 18:50
@galipmedia Thanks for reporting that bug, #1 is fixed in 1.0.9, just published.

As for the SocketCluster issue you're having it's hard to diagnose here with what's reported above. This library doesn't do anything special with SocketCluster - you could rewrite the "bridge" using SocketIO or something else really easily. I only chose it because it checked a lot of boxes for a project I was working on that needed a scalable and sophisticated back-end. But really my purpose here was those same bindings you're after.

One thing I've notice with SocketCluster is that it can be very finicky about how the `#handshake` message is sent - and not very good about logging until this point is reached. I would definitely try a vanilla install parallel to your project, or look at the raw network traffic. I've had frustrating connection issues like this twice, and both times they were handshake or auth issues...

**Comment by crrobinson14** [comment] 2018-07-31 18:51
Also make sure the URL is correct, ending with `/socketcluster/` with the trailing slash. See https://github.com/sacOO7/socketcluster-client-java/issues/2.

**Comment by galipmedia** [comment] 2018-08-01 05:08
@crrobinson14 You sir, are my hero! That trailing slash has saved my sanity! Everything is working perfectly now. Except I have commented out the subscribeAll function as it seems to just cause duplicate subscriptions. What is the purpose of this function?

**Comment by crrobinson14** [comment] 2018-08-13 17:26
@galipmedia `subscribeAll` is meant to be run on reconnections to resubscribe to all existing subs. Typical use case is a user on a train goes into a tunnel. I'm not seeing duplicate subs made on my side. Is there a pattern for reproducing this? Is it 100% of the time for you? It could be an undiscovered bug...

**Closed** 2020-04-10 16:22 UTC
